# Generated by Django 4.0.1 on 2022-01-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='phone',
            field=models.IntegerField(max_length=15),
        ),
    ]
