# Generated by Django 4.0.1 on 2022-01-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_custom_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
