# Generated by Django 4.0.1 on 2022-02-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=333)),
                ('last_name', models.CharField(max_length=333)),
                ('email', models.EmailField(max_length=333, unique=True)),
                ('phone', models.BigIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('skill1', models.CharField(max_length=333)),
                ('skill2', models.CharField(blank=True, max_length=333, null=True)),
                ('skill3', models.CharField(blank=True, max_length=333, null=True)),
                ('city', models.CharField(max_length=333)),
                ('address', models.TextField(max_length=333)),
                ('password', models.CharField(max_length=333)),
                ('description', models.TextField(blank=True, max_length=333, null=True)),
                ('subscription', models.CharField(max_length=333)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_worker', models.BooleanField(default=False)),
            ],
        ),
    ]
