# Generated by Django 4.0.1 on 2022-02-01 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_emp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='address',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='email',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='password',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='phone',
        ),
        migrations.AddField(
            model_name='emp',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emp',
            name='image',
            field=models.ImageField(blank=True, upload_to='emp'),
        ),
    ]
