# Generated by Django 4.0.1 on 2022-02-02 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_emp_address_remove_emp_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
