# Generated by Django 4.0.1 on 2022-02-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_emp_skill2_remove_emp_skill3_alter_emp_skill1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='skill1',
        ),
        migrations.AddField(
            model_name='emp',
            name='skill1',
            field=models.ManyToManyField(to='user.Skill'),
        ),
    ]
