# Generated by Django 4.0.1 on 2022-02-02 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_emp_skill1_emp_skill1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='skill1',
        ),
        migrations.AddField(
            model_name='emp',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.skill'),
            preserve_default=False,
        ),
    ]
