# Generated by Django 4.0.1 on 2022-02-03 16:00

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_emp_skill_emp_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='skill',
        ),
        migrations.AddField(
            model_name='emp',
            name='skill1',
            field=models.CharField(default=2, max_length=333),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp',
            name='skill2',
            field=models.CharField(blank=True, max_length=333, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='skill3',
            field=models.CharField(blank=True, max_length=333, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='image',
            field=models.ImageField(upload_to=user.models.upload_to, verbose_name='Image'),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
