# Generated by Django 4.0.1 on 2022-02-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_emp_skill_emp_skill1_emp_skill2_emp_skill3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='skill1',
            field=models.JSONField(verbose_name='Skill'),
        ),
    ]
