# Generated by Django 4.0.1 on 2022-02-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_emp_skill1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='skill1',
            field=models.JSONField(),
        ),
    ]
