# Generated by Django 4.0.1 on 2022-02-04 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_emp_skill1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='skill1',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='skill2',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='skill3',
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_1', models.JSONField()),
                ('skill_2', models.CharField(blank=True, max_length=333, null=True)),
                ('skill_3', models.CharField(blank=True, max_length=333, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
