# Generated by Django 4.0.1 on 2022-02-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_emp_skill1_remove_emp_skill2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_1',
            field=models.CharField(max_length=333),
        ),
    ]
