# Generated by Django 4.0.1 on 2022-02-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_skill_skill_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='skill',
            field=models.CharField(default=2, max_length=333),
            preserve_default=False,
        ),
    ]
